version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - baliyonet

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - baliyonet

  worker:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - baliyonet

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - baliyonet

volumes:
  redis_data:

networks:
  baliyonet:
    driver: bridge
